project:
  type: website

website:
  title: "ShapBio"
  site-url: https://shapbio.me/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.markdown
        text: Teaching
      - href: cv.html
        text: CV
format:
  html:
    theme: litera
    toc: true
reference-location: margin

editor: source

