project:
  type: website

website:
  title: "ShapBio"
  site-url: https://shapbio.me/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.markdown
        text: Teaching
      - href: cv.html
        text: CV
  page-footer:
    left: |
      Except as noted, all content on [shapbio.me]{xmlns:dct="http://purl.org/dc/terms/" property="dct:title"} by <a xmlns:cc="http://creativecommons.org/ns#" href="http://shapbio.me" property="cc:attributionName" rel="cc:attributionURL">Joshua A Shapiro</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.
    background: light

format:
  html:
    theme: litera
    toc: true
reference-location: margin

editor: source

