---
title: Teaching
---

Below are brief descriptions of some the courses that I have designed and taught recently, including links to syllabi.

## Introduction to Genomics [syllabus](docs/BiolB216_syllabus_fall2012.pdf){.file-link}

<blockquote>
<p>We shift over our fingers the first grains of this great outpouring of information and say to ourselves that the world be helped by it. …one small link in the chain from biochemistry and mathematics to sociology and medicine.</p>
<footer> <cite><a href="http://en.wikipedia.org/wiki/Margaret_Oakley_Dayhoff">Margaret Dayhoff</a> (<a href="http://dx.doi.org/10.1007/s10739-009-9221-0">Strasser 2010</a>)</cite> </footer>
</blockquote>

**What is a genome and what is it good for?**

This course introduces the questions that can be asked and answered with genomic data, and the  computational methods and resources available for analysis of such large biological data sets. Recent advances in technologies such as microarrays, DNA sequencing, and protein mass spectrometry have  transformed biology, making experiments easier, cheaper, and more accurate, while generating much more data than ever before. Taking advantage of this genomic data requires not only the ability to manage these data, but often new ways of thinking about biological questions. The course covers key concepts in bioinformatics, such as the use of public databases, sequence alignment and assembly, gene expression analysis, and structural modeling. The computational lab component of the course provides the opportunity to explore the applications of these concepts using both small-scale and genomic data. Because genomics is a rapidly progressing field, an important component of the course is the discussion of recent articles from the primary and popular science literature. We explore these advances not only for their scientific content, but also to examine their potential impacts on society.

## [Experimental Design and Statistics](courses/biolB215s19/index.html) [syllabus](courses/biolB215s18/BiolB215_syllabus_Sp2019.pdf){.file-link}

<blockquote>
<p>Statistics is applied philosophy of science.</p>
<footer><cite><a href='http://www.statslab.cam.ac.uk/~apd/'>A. P. Dawid</a> (<a href="http://www.worldcat.org/title/statistics-a-very-short-introduction/oclc/216938494">Hand 2008</a>)</cite></footer>
</blockquote>

**How do you use statistics to answer questions about biology and beyond?**

This course is designed to introduce the concepts and tools of statistics in a biological context. In addition to description of classical statistical methods, a substantial portion of the course is devoted to discussion of the how the concepts of statistics inform the design of experiments. We also explore the interpretation of data from experiments and observations that are not designed to an ideal standard (also known as *data*). A critical component of the class is the computational lab which introduces the [`R` statistics environment](http://www.r-project.org), a powerful and flexible system that is rapidly becoming the standard for statistical analysis in biology and elsewhere. We work with actual biological data as much as possible, learning how to handle issues like violations of assumptions, non-standard distributions, and multiple testing. Using `R` also allows the exploration of computationally intensive techniques such as simulation, permutation testing, and bootstrapping.

## Evolutionary Genetics and Genomics [syllabus](docs/BiolB327_syllabus_spring2012.pdf){.file-link}

<blockquote>
<p>…nothing makes sense in biology <br> except in the light of evolution, <em>sub specie evolutionis</em>.</p>
<footer><cite><a href='http://en.wikipedia.org/wiki/Theodosius_Dobzhansky'> Theodosius Dobzhansky</a> (<a href="http://dx.doi.org/10.1093/icb/4.4.443">Dobzhansky 1964</a>)</cite></footer>
</blockquote>

**How do changes in DNA sequences affect the evolution of organisms?**

This seminar focuses on topics in population genetics and molecular evolution, beginning our discussions by examining classic papers from the primary literature. Many of these classic papers are based on data from only one or a few genes, but advances in technology are now making it possible to revisit those questions with data from entire genomes. By comparing the classic papers with more recent work at done at genomic scales, we can see how the orignal models have been adapted and updated with the addition of more complete data. This new genomic data answers many long-standing questions, but also raises new questions and avenues of inquiry that we are only beginning to explore. Topics include the roles of selection and drift in molecular evolution, evolution of gene expression, genomic approaches to the study of quantitative variation, evolutionary history of humans, and evolutionary perspectives on the study of human disease. Students write weekly responses to the assigned readings, lead and participate in class discussions and debates, and write a final review paper on a topic of their choice.







