---
title: "Let's see how this goes"
description: "A bit about starting a personal blog"
author: "Josh"
date: "2023-01-01"
categories:
  - personal
  - meta
draft: true
---

I'm waiting on the new year as I write this.
I probably won't finish this post or publish it for a while yet, but it seemed a good time to start.
My personal website is horribly out of date, I had a bit of free time while visiting the in-laws, and there is a not-so-new literate programming engine on the block, so I thought I would try to get things going.

I've never had much luck with blogging.
I usually don't feel like I have much to say, and the effort to get posts up is usually beyond my motivation, so the blogs I've started in the past have never gotten more than a couple of posts.
If this one does better, well, fantastic.
We'll see how we go.

Just a couple of programming notes as we get started:

-   I'm rebuilding my website with [Quarto](https://quarto.org), which is the literate programming engine mentioned above.
    As an evolution of Rmarkdown, I'm pretty familiar with the basics, but not as much the full website features.
    Previously, I had used Jekyll, and had a fair amount of customization that I had built up in there... Most of that is being ripped out for now.
    Maybe I will customize more in the future, but as I age I have gotten less and less interested in tweaking things to be *just so*, as I usually regret it later.
    So, back to basics, sort of.

-   I expect most of my posts to include some code, mostly R, but probably some Python and Nextflow, since I've been spending chunks of time with each of those.
    I have no idea how long a post will usually be.
    Probably pretty short.
    If I set that expectation for myself, I might actually write some things.
    One thought is to try to use this blog as a place to make some notes as I discover tips and tricks that I want to record for myself, and others might find useful.
    I'll probably complain some about things that have frustrated me, but I'll try to be nice about it.
    And maybe people will read this and give tips.

-   Most posts will include R session information.
    Why?
    Partly because it is a habit I have gotten into in my work at the [Childhood Cancer Data Lab](https://ccdatalab.org), but partly because it seems like a good thing to do.
    If there is code in the blog post, I want to be able to see what version of the various packages I was working with when I come back years later.
    When rebuilding this site, I found a number of places where my code was old and broken.
    Some of those I updated, some I just deleted.
    Quarto makes it fairly easy to freeze results as they were produced, but I still want that record for future reference.
    It's neat to see how code and conventions evolve.
    This is probably a subject for a future post, if I can arrange my thoughts.
    But for now, let's just see what we were starting with as we got started with this new version of the site:

## Session information

<details>

<summary>R session information</summary>

```{r}
#| label: session info
sessioninfo::session_info()
```

</details>
