---
title: "Maybe this time"
description: "Look, I said it was irregular"
author: "Josh"
date: "2027-10-04"
categories:
  - personal
  - meta
---

I really did think two years ago that I was going to get the website up and running.
I really did.
I think I even got kind of close, but not close enough.
But now I think it might really happen, so I'm writing another post[^1].

If you look at the [code here](https://github.com/jashapiro/jashapiro.github.io), you will see that this time around I got some help with rewriting the code using Claude.
Specifically, I got it to help with the long-planned and long-delayed transition from Jekyll to Quarto.

What I did not do (and specifically banned in my [AGENTS.md file](https://github.com/jashapiro/jashapiro.github.io/blob/main/AGENTS.md)) is any AI assistance with writing content.
Everything you see as content is written by me, with some possible use of autocomplete suggestions within code blocks.

I can imagine a time when I may include some more AI-written code sections, but honestly I have some doubts about the extent to which I will include code much at all.
I had some plans to do that a couple of years ago (see [my post about session_info](../2025-03-02_session-info-security-through-obscurity)), but writing code is usually well handled by LLMs, so it seems a bit pointless.
On the other hand, the code I see the LLMs writing is often not really well done, so maybe more good examples are worth the effort.
Not that my code is always good!
I just had a look back through the code I had written for [my biostats class](../../courses/biolB215s19/index.qmd) and let's just say I wouldn't teach with that code these days.
So we'll see.

I'm kind of hopeful that I will be inspired to write some more, but I have been hopeful before.

[^1]: I think part of the reason I am motivated again is that for the first time in a while I have my own personal computer that I am explicitly not using for work.
This has to do with some changes in policies at work, but also the fact that I could get a cute little MacBook Neo, and dang if it isn't cute and fun.
Blue, if you were wondering.
